# Copyright (c) 2025 ADBC Drivers Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: cb8c523fd4835aba42af70f4cad5568db4df0b6c  # frozen: v0.16.0
  hooks:
    - id: ruff-check
      name: "ruff check (isort)"
      args: ["--select", "I", "--fix"]
    - id: ruff-check
      args: ["--fix"]
    - id: ruff-format

- repo: https://github.com/codespell-project/codespell
  rev: 57b21406f092110c18776e39b0bda50d37c945c8  # frozen: v2.4.3
  hooks:
  - id: codespell
    exclude: >
        (?x)^(
            .*go\.sum
        )$

- repo: https://github.com/golangci/golangci-lint
  rev: 9c5dd448ac26caa35e3faee1e8e94476ae885b0f  # frozen: v2.13.1
  hooks:
  - id: golangci-lint
    entry: bash -c 'cd go && golangci-lint run --fix --timeout 5m'
    types_or: [go, go-mod]

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c  # frozen: v6.0.0
  hooks:
  - id: check-added-large-files
    args: ["--enforce-all"]
  - id: check-case-conflict
  - id: check-executables-have-shebangs
  - id: check-yaml
  - id: detect-private-key
  - id: end-of-file-fixer
    exclude: '\.sln$'
  - id: mixed-line-ending
    args: [--fix=lf]
    exclude: '\.(bat|sln)$'
  - id: trailing-whitespace

- repo: https://github.com/adbc-drivers/dev
  rev: f9cc95795485149e339f8474853344e4e6870e93
  hooks:
  - id: rat

- repo: local
  hooks:
  - id: gofix
    name: go fix
    language: system
    types: [go]
    entry: bash -c 'cd go && go fix ./...'
    pass_filenames: false
