# Copyright (c) 2025 ADBC Drivers Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

ignore-lints = ["must-test-null-values"]

[tags]
field-type-name = [
    "ARRAY<BOOLEAN>",
    "ARRAY<BOOLEAN>",
    "ARRAY<INTEGER>",
    "ARRAY<INTEGER>",
    "ARRAY<STRING>",
    "ARRAY<STRING>",
]
sql-type-name = "ARRAY"
caveats = ["BigQuery treats NULL arrays as empty arrays in result sets, even though you can differentiate between them during query execution.  See https://cloud.google.com/bigquery/docs/reference/standard-sql/data-types#array_nulls for more details."]
