DROP TABLE IF EXISTS test_interval;

CREATE TABLE test_interval (
    idx INTEGER,
    res INTERVAL
);

INSERT INTO test_interval (idx, res)
VALUES
  (0, INTERVAL 1 YEAR),
  (1, INTERVAL 1 QUARTER),
  (2, INTERVAL 1 MONTH),
  (3, INTERVAL 1 DAY),
  (4, INTERVAL 1 HOUR),
  (5, INTERVAL 1 MINUTE),
  (6, INTERVAL 1 SECOND),
  (7, INTERVAL 1 MILLISECOND),
  (8, INTERVAL 1 MICROSECOND),
  (9, INTERVAL '1-2' YEAR TO MONTH),
  (10, INTERVAL '1 15' MONTH TO DAY),
  (11, INTERVAL '-10-1 5 -12:30:01' YEAR TO SECOND),
  (12, NULL)
;
